name: Release Example Binary

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    strategy:
      matrix:
        go-version: [1.17.x] #, 1.16.x 
        # build and publish in parallel: linux/amd64
        goos: [linux]
        goarch: [amd64]
        os: [ubuntu-latest] #, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          cd W2/example && go test ./...
      - name: create release
        uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./W2/example"
          binary_name: "example.exe"
          #ldflags: "-s -w"
          extra_files: README.md
